export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'; 

export const REQUEST_AUTOBOTS_PENDING = 'REQUEST_AUTOBOTS_PENDING';
export const REQUEST_AUTOBOTS_SUCCESS = 'REQUEST_AUTOBOTS_SUCCESS';
export const REQUEST_AUTOBOTS_FAILED = 'REQUEST_AUTOBOTS_FAILED';